// Author: huangbingrui.awa
import {describe, expect, it} from 'vitest'
import {readFileSync} from 'node:fs'
import {resolve} from 'node:path'

const indexSource = readFileSync(resolve(process.cwd(), 'src/views/Index.vue'), 'utf8')
const featuredSource = readFileSync(resolve(process.cwd(), 'src/components/sidebar/FeaturedBlog.vue'), 'utf8')
const tocSource = readFileSync(resolve(process.cwd(), 'src/components/sidebar/Tocbot.vue'), 'utf8')

describe('desktop article workbench', () => {
	it('splits article pages into an independently scrolling tool sidebar and reading pane', () => {
		expect(indexSource.match(/class="sticky-sidebar/g)).toHaveLength(1)
		expect(indexSource).toContain("'has-article-sidebar': $route.name === 'blog'")
		expect(indexSource).toContain('grid-template-columns: clamp(272px, 20vw, 320px) minmax(0, 1fr);')
		expect(indexSource).toContain('class="sticky-sidebar article-sidebar"')
		expect(indexSource).toContain("'article-reading-pane': $route.name === 'blog'")
		expect(indexSource).toContain('.article-sidebar {')
		expect(indexSource).toContain('.article-reading-pane {')
		expect(indexSource).toContain('grid-template-rows: minmax(0, 1fr);')
		expect(indexSource).toMatch(/\.site\.is-article \.main-grid \{[\s\S]*overflow: hidden;/)
		expect(indexSource).toMatch(/\.article-sidebar-column \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
		expect(indexSource).toMatch(/\.article-sidebar \{[\s\S]*max-height: 100%;[\s\S]*overflow-y: auto;/)
		expect(indexSource).toMatch(/\.article-sidebar > \* \{[\s\S]*flex-shrink: 0;/)
		expect(indexSource).toContain('overflow-y: auto;')
		expect(indexSource).toContain('overflow-x: clip;')
	})

	it('uses the shared light glass navigation on the article catalog', () => {
		expect(indexSource).toContain('padding-inline: 2rem;')
		expect(indexSource).toContain('padding-inline: 1rem;')
		expect(indexSource).toContain('--home-canvas: var(--anthropic-ivory-light);')
		expect(indexSource).toContain('--home-surface: #f7f7f5;')
		expect(indexSource).toContain('--home-text: #050505;')
		expect(indexSource).toContain('--home-text-soft: #37352f;')
		expect(indexSource).toContain('--home-border: #e9e9e7;')
		expect(indexSource).toMatch(/\.site\.is-catalog,[\s\S]*background: var\(--anthropic-ivory-light\);[\s\S]*color: var\(--anthropic-slate-dark\);/)
		expect(indexSource).toMatch(/\.site\.is-catalog :deep\(\.site-nav\) \{[\s\S]*background: var\(--glass-background\) !important;[\s\S]*backdrop-filter: var\(--glass-filter\);/)
		expect(indexSource).toContain('border-bottom-color: var(--glass-border) !important;')
		expect(indexSource).toMatch(/\.site\.is-catalog :deep\(\.site-nav \.nav-item\),[\s\S]*color: var\(--color-text\) !important;/)
		expect(indexSource).toContain('background: var(--color-action) !important;')
		expect(indexSource).not.toContain('.site.is-home :deep(.site-nav) {')
		expect(indexSource).not.toContain('.site.is-article :deep(.site-nav),')
		expect(indexSource).not.toContain('.site.is-editor :deep(.site-nav) {')
		expect(indexSource).not.toContain('data-theme="dark"')
		expect(featuredSource).toContain('margin: 1.5rem 0 2rem;')
	})

	it('groups author, table of contents and the comment shortcut in the left tool pane', () => {
		expect(indexSource).toContain('class="m-mobile-hide sidebar-column article-sidebar-column"')
		expect(indexSource.indexOf('<Introduction')).toBeLessThan(indexSource.indexOf('<Tocbot'))
		expect(indexSource.indexOf('<Tocbot')).toBeLessThan(indexSource.indexOf('class="article-comment-shortcut"'))
		expect(indexSource).toContain('href="#article-comments"')
		expect(indexSource).toContain('<AppIcon name="chevron-down" />')
		expect(indexSource).toContain('<em>{{ allComment }}</em>')
		expect(indexSource).not.toContain('跳到完整讨论')
		expect(indexSource).toContain('margin-top: auto;')
		expect(indexSource).toContain('min-height: 32px;')
		expect(indexSource).toContain('border-bottom: 0;')
		expect(indexSource).toContain('.article-sidebar :deep(.m-toc)')
		expect(indexSource.match(/border-bottom: 0 !important;/g)?.length).toBeGreaterThanOrEqual(3)
		expect(indexSource).toContain("pane.scrollTo({top, behavior: 'smooth'})")
		expect(indexSource).toContain('<FeaturedBlog v-if="$route.name === \'home\'"')
		expect(indexSource).toContain('<router-view v-if="$route.name !== \'home\'"')
		expect(indexSource.indexOf('<FeaturedBlog')).toBeLessThan(indexSource.indexOf('<router-view v-if="$route.name !== \'home\'"'))
		expect(indexSource).not.toContain('<Tags')
		expect(indexSource).not.toContain('import Tags')
		expect(tocSource).not.toContain('positionFixedSelector')
		expect(tocSource).not.toContain('.m-toc.is-position-fixed')
		expect(tocSource).toContain("scrollContainer: '.article-reading-pane'")
		expect(tocSource).toMatch(/\.m-toc \.toc \{[\s\S]*overflow: visible/)
		expect(tocSource).toContain('-webkit-line-clamp: 2;')
		expect(tocSource).toContain('line-clamp: 2;')
		expect(tocSource).toContain('overflow-wrap: anywhere;')
		expect(tocSource).toContain('text-overflow: ellipsis;')
	})

	it('makes the author avatar the dominant element in the article sidebar', () => {
		expect(indexSource).not.toContain('article-sidebar-label')
		expect(indexSource).not.toContain('<small>ARTICLE</small>')
		expect(indexSource).toContain('grid-template-columns: minmax(0, 1fr);')
		expect(indexSource).toContain('.article-sidebar :deep(.profile-avatar-shell)')
		expect(indexSource).toContain('width: 100%;')
		expect(indexSource).toContain('aspect-ratio: 1;')
		expect(indexSource).toContain('border-radius: 20px;')
	})
})
