insert into ods_atcoder__submission (
    atcoder_submission_id,
    epoch_second,
    problem_id,
    contest_id,
    user_id,
    language,
    point,
    source_code_length,
    result,
    execution_time_millis,
    batch_id,
    fetched_at,
    raw_payload,
    payload_hash
) values (
    :atcoderSubmissionId,
    :epochSecond,
    :problemId,
    :contestId,
    :userId,
    :language,
    :point,
    :sourceCodeLength,
    :result,
    :executionTimeMillis,
    :batchId,
    :fetchedAt,
    :rawPayload,
    :payloadHash
)
on duplicate key update
    epoch_second = values(epoch_second),
    problem_id = values(problem_id),
    contest_id = values(contest_id),
    user_id = values(user_id),
    language = values(language),
    point = values(point),
    source_code_length = values(source_code_length),
    result = values(result),
    execution_time_millis = values(execution_time_millis),
    batch_id = values(batch_id),
    fetched_at = values(fetched_at),
    raw_payload = values(raw_payload),
    payload_hash = values(payload_hash),
    updated_at = current_timestamp(6);
