insert into ods_atcoder__problem_model (
    problem_id,
    slope,
    intercept,
    variance,
    raw_difficulty,
    clipped_difficulty,
    discrimination,
    irt_loglikelihood,
    irt_users,
    is_experimental,
    batch_id,
    fetched_at,
    raw_payload,
    payload_hash
) values (
    :problemId,
    :slope,
    :intercept,
    :variance,
    :rawDifficulty,
    :clippedDifficulty,
    :discrimination,
    :irtLogLikelihood,
    :irtUsers,
    :experimental,
    :batchId,
    :fetchedAt,
    :rawPayload,
    :payloadHash
)
on duplicate key update
    slope = values(slope),
    intercept = values(intercept),
    variance = values(variance),
    raw_difficulty = values(raw_difficulty),
    clipped_difficulty = values(clipped_difficulty),
    discrimination = values(discrimination),
    irt_loglikelihood = values(irt_loglikelihood),
    irt_users = values(irt_users),
    is_experimental = values(is_experimental),
    batch_id = values(batch_id),
    fetched_at = values(fetched_at),
    raw_payload = values(raw_payload),
    payload_hash = values(payload_hash),
    updated_at = current_timestamp(6);
