#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_FILE="${ROOT_DIR}/frontend-design-tokens/tokens.css"
TRAINING_FILE="${ROOT_DIR}/frontend/src/styles/tokens.css"
BLOG_FILE="${ROOT_DIR}/platform-blog/upstream/nblog/blog-view/src/assets/css/tokens.css"
GENERATED_HEADER='/* GENERATED by scripts/sync-design-tokens.sh. DO NOT EDIT. */'

usage() {
  cat <<'EOF'
Usage:
  ./scripts/sync-design-tokens.sh
  ./scripts/sync-design-tokens.sh --check

Without arguments, refreshes both frontend-local generated token files.
With --check, exits non-zero when either generated file is stale.
EOF
}

MODE="${1:-sync}"
if [[ "${MODE}" == "-h" || "${MODE}" == "--help" || "${MODE}" == "help" ]]; then
  usage
  exit 0
fi
if [[ "${MODE}" != "sync" && "${MODE}" != "--check" ]]; then
  usage >&2
  exit 2
fi
if [[ ! -f "${SOURCE_FILE}" ]]; then
  echo "Missing token source: ${SOURCE_FILE}" >&2
  exit 1
fi

EXPECTED_FILE="$(mktemp "${TMPDIR:-/tmp}/custacm-design-tokens.XXXXXX")"
trap 'rm -f "${EXPECTED_FILE}"' EXIT
{
  printf '%s\n' "${GENERATED_HEADER}"
  cat "${SOURCE_FILE}"
} >"${EXPECTED_FILE}"

if [[ "${MODE}" == "--check" ]]; then
  stale=0
  for target in "${TRAINING_FILE}" "${BLOG_FILE}"; do
    if [[ ! -f "${target}" ]] || ! cmp -s "${EXPECTED_FILE}" "${target}"; then
      echo "Generated design tokens are stale: ${target#"${ROOT_DIR}/"}" >&2
      stale=1
    fi
  done
  if [[ "${stale}" == "1" ]]; then
    echo "Run ./scripts/sync-design-tokens.sh and commit the generated files." >&2
    exit 1
  fi
  echo "Design token check passed."
  exit 0
fi

for target in "${TRAINING_FILE}" "${BLOG_FILE}"; do
  mkdir -p "$(dirname "${target}")"
  cp "${EXPECTED_FILE}" "${target}"
  echo "Updated ${target#"${ROOT_DIR}/"}"
done
