create table if not exists ods_codeforces__submission (
    id bigint primary key auto_increment,
    codeforces_submission_id bigint not null,
    contest_id bigint null,
    creation_time_seconds bigint null,
    relative_time_seconds int null,
    problem_contest_id bigint null,
    problem_index varchar(32) null,
    problem_name varchar(255) null,
    problem_type varchar(64) null,
    problem_points decimal(12, 4) null,
    problem_rating int null,
    problem_tags_json longtext null,
    author_handle varchar(128) not null,
    author_participant_type varchar(64) null,
    author_json longtext null,
    programming_language varchar(128) null,
    verdict varchar(64) null,
    testset varchar(64) null,
    passed_test_count int null,
    time_consumed_millis int null,
    memory_consumed_bytes bigint null,
    batch_id varchar(128) not null,
    fetched_at datetime(6) not null,
    raw_payload longtext not null,
    payload_hash char(64) not null,
    created_at datetime(6) not null default current_timestamp(6),
    updated_at datetime(6) not null default current_timestamp(6),
    unique key uk_ods_codeforces_submission_source (codeforces_submission_id),
    index idx_ods_codeforces_submission_author_time (author_handle, creation_time_seconds),
    index idx_ods_codeforces_submission_problem (contest_id, problem_index),
    index idx_ods_codeforces_submission_batch (batch_id)
);
