create table if not exists dwd_codeforces__submission (
    id bigint primary key auto_increment,
    ods_submission_id bigint not null,
    codeforces_submission_id bigint not null,
    author_handle varchar(128) not null,
    contest_id bigint null,
    submitted_at datetime(6) null,
    submitted_date_utc date null,
    relative_time_seconds int null,
    problem_key varchar(96) null,
    problem_contest_id bigint null,
    problem_index varchar(32) null,
    problem_name varchar(255) null,
    problem_type varchar(64) null,
    problem_points decimal(12, 4) null,
    problem_rating int null,
    problem_tags_json longtext null,
    author_participant_type varchar(64) null,
    programming_language varchar(128) null,
    verdict varchar(64) null,
    is_accepted tinyint(1) not null,
    testset varchar(64) null,
    passed_test_count int null,
    time_consumed_millis int null,
    memory_consumed_bytes bigint null,
    ods_batch_id varchar(128) not null,
    ods_fetched_at datetime(6) not null,
    ods_payload_hash char(64) not null,
    created_at datetime(6) not null default current_timestamp(6),
    updated_at datetime(6) not null default current_timestamp(6),
    unique key uk_dwd_codeforces_submission_source (codeforces_submission_id),
    index idx_dwd_codeforces_submission_ods (ods_submission_id),
    index idx_dwd_codeforces_handle_time (author_handle, submitted_at),
    index idx_dwd_codeforces_problem (problem_key),
    index idx_dwd_codeforces_accepted (is_accepted, author_handle, problem_key, submitted_at)
);

create table if not exists dwm_codeforces__handle_problem_first_accepted (
    id bigint primary key auto_increment,
    author_handle varchar(128) not null,
    problem_key varchar(96) not null,
    problem_contest_id bigint not null,
    problem_index varchar(32) not null,
    problem_name varchar(255) null,
    problem_type varchar(64) null,
    problem_points decimal(12, 4) null,
    problem_rating int null,
    problem_tags_json longtext null,
    first_accepted_submission_id bigint not null,
    first_accepted_at datetime(6) not null,
    first_accepted_date_utc date not null,
    first_accepted_language varchar(128) null,
    created_at datetime(6) not null default current_timestamp(6),
    updated_at datetime(6) not null default current_timestamp(6),
    unique key uk_dwm_codeforces_handle_problem (author_handle, problem_key),
    index idx_dwm_codeforces_first_accepted_handle_date (author_handle, first_accepted_date_utc),
    index idx_dwm_codeforces_first_accepted_problem_rating (problem_rating)
);

create table if not exists dws_codeforces__handle_daily_rating_accepted_summary (
    id bigint primary key auto_increment,
    author_handle varchar(128) not null,
    accepted_date_utc date not null,
    problem_rating_key varchar(32) not null,
    problem_rating int null,
    accepted_problem_count int not null,
    created_at datetime(6) not null default current_timestamp(6),
    updated_at datetime(6) not null default current_timestamp(6),
    unique key uk_dws_codeforces_handle_date_rating (
        author_handle,
        accepted_date_utc,
        problem_rating_key
    ),
    index idx_dws_codeforces_daily_rating_date_rating (accepted_date_utc, problem_rating_key)
);
