package com.custacm.platform.common.sqltask;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

import javax.sql.DataSource;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SqlTaskRunnerTest {
    private JdbcTemplate jdbcTemplate;
    private SqlTaskRunner runner;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:sql_task_" + UUID.randomUUID()
                        + ";MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table sql_task_test_log (
                    id bigint generated by default as identity primary key,
                    step_name varchar(32) not null,
                    marker int not null,
                    note varchar(255) not null
                )
                """);
        runner = new SqlTaskRunner(
                new NamedParameterJdbcTemplate(dataSource),
                new DataSourceTransactionManager(dataSource),
                new DefaultResourceLoader()
        );
    }

    @Test
    void executesYamlDagInTopologicalOrder() {
        SqlTaskExecutionResult result = runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/valid.yml",
                Map.of("marker", 7),
                null
        ));

        assertThat(result.status()).isEqualTo(SqlTaskRunStatus.SUCCESS);
        assertThat(result.runId()).isNotBlank();
        assertThat(result.failedTaskId()).isNull();
        assertThat(result.tasks())
                .extracting(SqlTaskNodeResult::taskId)
                .containsExactly("load-a", "load-b", "load-c");
        assertThat(result.tasks())
                .extracting(SqlTaskNodeResult::status)
                .containsExactly(SqlTaskNodeStatus.SUCCESS, SqlTaskNodeStatus.SUCCESS, SqlTaskNodeStatus.SUCCESS);
        assertThat(stepNames()).containsExactly("A", "B", "C");
        assertThat(markers()).containsExactly(7, 7, 7);
    }

    @Test
    void startFromTaskExecutesRequestedNodeAndDownstreamOnly() {
        SqlTaskExecutionResult result = runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/valid.yml",
                Map.of("marker", 8),
                "load-b"
        ));

        assertThat(result.status()).isEqualTo(SqlTaskRunStatus.SUCCESS);
        assertThat(result.startFromTaskId()).isEqualTo("load-b");
        assertThat(result.tasks())
                .extracting(SqlTaskNodeResult::taskId)
                .containsExactly("load-b", "load-c");
        assertThat(stepNames()).containsExactly("B", "C");
    }

    @Test
    void invalidDagIsRejectedBeforeExecution() {
        assertThatThrownBy(() -> runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/cycle.yml",
                Map.of("marker", 9),
                null
        )))
                .isInstanceOf(SqlTaskException.class)
                .extracting(ex -> ((SqlTaskException) ex).errorCode())
                .isEqualTo(SqlTaskErrorCode.SQL_TASK_DAG_INVALID);

        assertThat(countRows()).isZero();
    }

    @Test
    void missingDependencyIsRejectedBeforeExecution() {
        assertThatThrownBy(() -> runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/missing-dependency.yml",
                Map.of("marker", 10),
                null
        )))
                .isInstanceOf(SqlTaskException.class)
                .extracting(ex -> ((SqlTaskException) ex).errorCode())
                .isEqualTo(SqlTaskErrorCode.SQL_TASK_CONFIG_INVALID);

        assertThat(countRows()).isZero();
    }

    @Test
    void nodeFailureStopsDagSkipsDownstreamAndRollsBackFailedNodeTransaction() {
        SqlTaskExecutionResult result = runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/failing.yml",
                Map.of("marker", 11),
                null
        ));

        assertThat(result.status()).isEqualTo(SqlTaskRunStatus.FAILED);
        assertThat(result.failedTaskId()).isEqualTo("fail-b");
        assertThat(result.tasks())
                .extracting(SqlTaskNodeResult::taskId)
                .containsExactly("load-a", "fail-b", "load-c");
        assertThat(result.tasks())
                .extracting(SqlTaskNodeResult::status)
                .containsExactly(SqlTaskNodeStatus.SUCCESS, SqlTaskNodeStatus.FAILED, SqlTaskNodeStatus.SKIPPED);
        assertThat(result.tasks().get(1).errorCode()).isEqualTo("SQL_TASK_SQL_EXECUTION_FAILED");
        assertThat(stepNames()).containsExactly("A");
    }

    @Test
    void unknownStartFromTaskIsRejectedBeforeExecution() {
        assertThatThrownBy(() -> runner.execute(new SqlTaskExecutionRequest(
                "classpath:sqltask/valid.yml",
                Map.of("marker", 12),
                "missing"
        )))
                .isInstanceOf(SqlTaskException.class)
                .extracting(ex -> ((SqlTaskException) ex).errorCode())
                .isEqualTo(SqlTaskErrorCode.SQL_TASK_START_NODE_INVALID);

        assertThat(countRows()).isZero();
    }

    @Test
    void executionRequestKeepsNullParameterValuesForJdbcBinding() {
        Map<String, Object> parameters = new LinkedHashMap<>();
        parameters.put("nullableValue", null);

        SqlTaskExecutionRequest request = new SqlTaskExecutionRequest(
                "classpath:sqltask/valid.yml",
                parameters,
                null
        );

        assertThat(request.parameters()).containsKey("nullableValue");
        assertThat(request.parameters().get("nullableValue")).isNull();
    }

    private List<String> stepNames() {
        return jdbcTemplate.queryForList(
                "select step_name from sql_task_test_log order by id",
                String.class
        );
    }

    private List<Integer> markers() {
        return jdbcTemplate.queryForList(
                "select marker from sql_task_test_log order by id",
                Integer.class
        );
    }

    private int countRows() {
        return jdbcTemplate.queryForObject("select count(*) from sql_task_test_log", Integer.class);
    }
}
